# Generated by Django 3.0.4 on 2020-04-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200408_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('discription', models.TextField(max_length=1000, verbose_name='Описание')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d', verbose_name='Видео')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
