# Generated by Django 3.0.4 on 2020-04-08 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200408_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
